/*
 * This is sample code generated by rpcgen.
 * These are only templates and you can use them
 * as a guideline for developing your own functions.
 */

#include "calc.h"

int *
suma_1_svc(dupla_int *argp, struct svc_req *rqstp)
{
	static int  result;

	result = argp->x + argp->y;
	printf("Suma: %d + %d = %d\n", argp->x, argp->y, result);

	return &result;
}

int *
resta_1_svc(dupla_int *argp, struct svc_req *rqstp)
{
	static int  result;

	result = argp->x - argp->y;
	printf("Resta: %d - %d = %d\n", argp->x, argp->y, result);

	return &result;
}

int *
multiplicacion_1_svc(dupla_int *argp, struct svc_req *rqstp)
{
	static int  result;

	result = argp->x * argp->y;
	printf("Multiplicacion: %d * %d = %d\n", argp->x, argp->y, result);

	return &result;
}

int *
division_1_svc(dupla_int *argp, struct svc_req *rqstp)
{
	static int  result;

	result = argp->x / argp->y;
	printf("Division: %d / %d = %d\n", argp->x, argp->y, result);

	return &result;
}
