/*
 * This is sample code generated by rpcgen.
 * These are only templates and you can use them
 * as a guideline for developing your own functions.
 */

#include "calc.h"

void calc_prog_1(char *host, dupla_int *params, int *result, int operacion) {
  CLIENT *clnt;

#ifndef DEBUG
  clnt = clnt_create(host, CALC_PROG, CALC_VERS, "udp");
  if (clnt == NULL) {
    clnt_pcreateerror(host);
    exit(1);
  }
#endif /* DEBUG */

  switch (operacion) {
  case 1:
    *result = *suma_1(params, clnt);
    break;
  case 2:
    *result = *resta_1(params, clnt);
    break;
  case 3:
    *result = *multiplicacion_1(params, clnt);
    break;
  case 4:
    *result = *division_1(params, clnt);
    break;
  default:
    printf("Operacion no soportada\n");
    break;
  }

#ifndef DEBUG
  clnt_destroy(clnt);
#endif /* DEBUG */
}

int menuCalculadora() {
  int operacion;
  printf("1. Suma\n");
  printf("2. Resta\n");
  printf("3. Multiplicacion\n");
  printf("4. Division\n");
  printf("5. Salir\n");
  printf("Operacion: ");
  scanf("%d", &operacion);
  return operacion;
}

int main(int argc, char *argv[]) {
  char *host;

  if (argc < 2) {
    printf("usage: %s server_host\n", argv[0]);
    exit(1);
  }
  host = argv[1];

  int result;
  int operacion;
  dupla_int params;

  // Menu inicial
  operacion = menuCalculadora();

  while (operacion != 5) {

    // Parametros
    printf("Primer numero: ");
    scanf("%d", &params.x);
    printf("Segundo numero: ");
    scanf("%d", &params.y);

    calc_prog_1(host, &params, &result, operacion);
    printf("Resultado: %d\n", result);

    operacion = menuCalculadora();
  }
  exit(0);
}
